In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_selection import VarianceThreshold

In [2]:
features=pd.read_csv(r'C:\Users\Asus\PredictingRatings\data\features.csv')
#features=pd.read_csv(r'C:\Users\vznam\Downloads\PredictingRatings-master\data\features.csv')

print(features.info())
print(features.shape)
features.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24255 entries, 0 to 24254
Columns: 233 entries, Result to InsufficientMaterial
dtypes: float64(111), int64(122)
memory usage: 43.1 MB
None
(24255, 233)

,Result,NumMoves,MeanScore,ModeScore,FinalScore,FullMoves,MinScore,MaxScore,MedianScore,StdScore,...,EndB,EndR,EndK,WhiteСhecks,WhiteQueenCastle,BlackQueenCastle,Promotion,EnPassant,CanClaimDraw,InsufficientMaterial
count,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,...,24255.000000,24255.00000,24255.0,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000
mean,0.544877,42.252690,30.881103,11.907442,111.901711,83.967223,-794.591878,988.643950,68.913894,314.678490,...,0.631293,1.03892,1.0,2.015584,1.457308,0.910740,0.064069,0.061637,0.035415,0.000783
std,0.417736,16.235593,233.709202,445.214702,2310.851869,32.489872,2126.099646,2275.840558,64.170646,475.478471,...,0.676858,0.74847,0.0,2.874868,4.179615,3.663225,0.291749,0.245589,0.184831,0.027978
min,0.000000,10.000000,-2162.262500,-11447.000000,-12261.000000,19.000000,-12348.000000,-51.000000,0.000000,7.795716,...,0.000000,0.00000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,31.000000,-60.758665,0.000000,-362.000000,61.000000,-482.000000,67.000000,30.000000,61.336328,...,0.000000,0.00000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.500000,40.000000,24.563636,0.000000,0.000000,79.000000,-75.000000,156.000000,49.000000,145.621548,...,1.000000,1.00000,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,51.000000,123.987715,26.000000,546.500000,102.000000,-18.000000,700.000000,84.000000,291.317992,...,1.000000,2.00000,1.0,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,165.000000,2073.289256,11259.000000,12337.000000,329.000000,26.000000,12352.000000,784.000000,3962.575036,...,2.000000,2.00000,1.0,71.000000,35.000000,36.000000,4.000000,2.000000,1.000000,1.000000

In [3]:
cols=features.columns
for c in cols:
    if c.find('End') != -1:
        print(c)

MinEndScore
MaxEndScore
MeanEndScore
MedianEndScore
StdEndScore
VarianceEndScore
ModeEndScore
MinWhiteEndScore
MaxWhiteEndScore
MeanWhiteEndScore
MedianWhiteEndScore
StdWhiteEndScore
VarianceWhiteEndScore
ModeWhiteEndScore
FinalWhiteEndScore
MinBlackEndScore
MaxBlackEndScore
MeanBlackEndScore
MedianBlackEndScore
StdBlackEndScore
VarianceBlackEndScore
ModeBlackEndScore
FinalBlackEndScore
MinEndDeltaScore
MaxEndDeltaScore
MeanEndDeltaScore
MedianEndDeltaScore
StdEndDeltaScore
VarianceEndDeltaScore
ModeEndDeltaScore
MinWhiteEndDeltaScore
MaxWhiteEndDeltaScore
MeanWhiteEndDeltaScore
MedianWhiteEndDeltaScore
StdWhiteEndDeltaScore
VarianceWhiteEndDeltaScore
ModeWhiteEndDeltaScore
MinBlackEndDeltaScore
MaxBlackEndDeltaScore
MeanBlackEndDeltaScore
MedianBlackEndDeltaScore
StdBlackEndDeltaScore
VarianceBlackEndDeltaScore
ModeBlackEndDeltaScore
IndEndError
IndEndBlunder
IndWhiteEndError
IndWhiteEndBlunder
IndBlackEndError
IndBlackEndBlunder
NumEndErrors
NumEndBlunders
NumWhiteEndErrors
NumWhiteEndBlunders
NumBlackEndErrors
NumBlackEndBlunders
Endr
Endk
Endp
Endb
Endn
Endq
EndN
EndP
EndQ
EndB
EndR
EndK

In [4]:
from sklearn.feature_selection import VarianceThreshold

sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel_fit = sel.fit(features)
transform=sel_fit.transform(features)
features_new=pd.DataFrame(transform)
features_new.shape

(24255, 224)

In [5]:
inv_trans=sel_fit.inverse_transform(features_new)
inv_features=pd.DataFrame(inv_trans)
reject_features=inv_features.columns[(inv_features== 0).all()]
reject_features

Int64Index([183, 185, 187, 215, 225, 229, 230, 231, 232], dtype='int64')

In [6]:
rej=[]
for ind,val in enumerate(reject_features):
    rej.append(features.columns[val])
    print(features.columns[val])

NumDebBlunders
NumWhiteDebBlunders
NumBlackDebBlunders
Endk
EndK
Promotion
EnPassant
CanClaimDraw
InsufficientMaterial

In [7]:
reject_columns=pd.Series(rej)
reject_columns

0          NumDebBlunders
1     NumWhiteDebBlunders
2     NumBlackDebBlunders
3                    Endk
4                    EndK
5               Promotion
6               EnPassant
7            CanClaimDraw
8    InsufficientMaterial
dtype: object

In [12]:
reject_columns.to_csv(r'C:\Users\Asus\PredictingRatings\data\reject_columns.csv',sep=',',index=False)

In [8]:
features=pd.read_csv(r'C:\Users\Asus\PredictingRatings\data\features_new.csv')
features.head()

,0,1,2,3,4,5,6,7,8,9,...,214,215,216,217,218,219,220,221,222,223
0,0.5,19.0,23.947368,3.0,54.0,38.0,-26.0,73.0,20.5,26.431587,...,1.0,1.0,1.0,6.0,1.0,1.0,2.0,0.0,0.0,0.0
1,0.0,53.0,-692.198113,18.0,-11544.0,106.0,-11544.0,93.0,63.0,2286.131735,...,0.0,0.0,0.0,2.0,0.0,0.0,1.0,4.0,0.0,0.0
2,1.0,39.0,49.246753,31.0,196.0,77.0,-30.0,198.0,37.0,51.525093,...,0.0,0.0,1.0,4.0,0.0,0.0,1.0,1.0,0.0,0.0
3,1.0,25.0,306.040816,18.0,875.0,49.0,10.0,917.0,142.0,313.263595,...,1.0,1.0,1.0,4.0,1.0,2.0,2.0,0.0,0.0,0.0
4,0.5,29.0,30.827586,18.0,-11.0,58.0,-15.0,94.0,29.0,24.845827,...,0.0,1.0,0.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0

In [13]:
corr=features.corr(method='pearson')
corr.head()

,0,1,2,3,4,5,6,7,8,9,...,214,215,216,217,218,219,220,221,222,223
0,1.000000,-0.032734,0.680422,0.154037,0.567336,-0.043769,0.436827,0.407523,0.087790,0.002583,...,0.030724,-0.002891,0.010081,0.152286,0.063903,0.062679,0.068787,-0.145652,0.022463,-0.001100
1,-0.032734,1.000000,-0.016992,-0.013831,0.000671,0.999882,-0.194297,0.191654,0.146977,0.252136,...,-0.347062,-0.396261,-0.344839,-0.696870,-0.393259,-0.375284,-0.501649,0.561510,-0.030204,-0.008063
2,0.680422,-0.016992,1.000000,0.381663,0.751580,-0.024856,0.631160,0.646303,0.116982,0.052224,...,0.004141,-0.027855,0.017338,0.132040,0.069414,0.066542,0.050717,-0.133252,0.022777,0.004563
3,0.154037,-0.013831,0.381663,1.000000,0.190907,-0.015617,0.192575,0.167771,0.018366,-0.009792,...,0.005960,-0.015134,0.010604,0.039140,0.019678,0.034899,0.023327,-0.053992,0.002986,-0.002107
4,0.567336,0.000671,0.751580,0.190907,1.000000,-0.005774,0.628106,0.644216,0.068602,0.047178,...,-0.006523,-0.020712,0.008273,0.094997,0.038081,0.037475,0.027011,-0.081362,0.011280,-0.000963

In [14]:
indexes=corr.index
corr_feat=[]
corr_index=[]
corr_columns=[]
for index in corr.index:
    for column in corr.index:
        if index < column and abs(corr.loc[index,column])>=0.9:
            corr_feat.append((index,column))
            corr_index.append(index)
            corr_columns.append(column)
            
print(len(corr_feat))
corr_feat

172

[('1', '5'),
 ('2', '21'),
 ('2', '64'),
 ('2', '71'),
 ('2', '79'),
 ('4', '76'),
 ('4', '84'),
 ('6', '62'),
 ('6', '69'),
 ('6', '77'),
 ('7', '70'),
 ('7', '78'),
 ('10', '9'),
 ('10', '15'),
 ('10', '16'),
 ('10', '23'),
 ('10', '24'),
 ('10', '66'),
 ('10', '67'),
 ('10', '74'),
 ('10', '82'),
 ('11', '6'),
 ('11', '62'),
 ('11', '69'),
 ('12', '7'),
 ('12', '63'),
 ('12', '70'),
 ('13', '2'),
 ('13', '21'),
 ('13', '64'),
 ('13', '71'),
 ('13', '79'),
 ('14', '8'),
 ('14', '22'),
 ('15', '9'),
 ('15', '16'),
 ('15', '66'),
 ('15', '73'),
 ('15', '74'),
 ('16', '9'),
 ('16', '67'),
 ('16', '73'),
 ('16', '74'),
 ('18', '4'),
 ('18', '76'),
 ('19', '6'),
 ('19', '62'),
 ('19', '77'),
 ('20', '7'),
 ('20', '63'),
 ('20', '78'),
 ('21', '64'),
 ('21', '71'),
 ('21', '79'),
 ('22', '8'),
 ('23', '9'),
 ('23', '24'),
 ('23', '66'),
 ('23', '81'),
 ('23', '82'),
 ('24', '67'),
 ('24', '81'),
 ('24', '82'),
 ('26', '4'),
 ('26', '84'),
 ('27', '31'),
 ('27', '41'),
 ('27', '45'),
 ('27', '99'),
 ('28', '31'),
 ('28', '35'),
 ('28', '38'),
 ('29', '4'),
 ('31', '32'),
 ('31', '38'),
 ('31', '45'),
 ('31', '66'),
 ('31', '99'),
 ('32', '39'),
 ('35', '38'),
 ('38', '39'),
 ('41', '45'),
 ('41', '99'),
 ('45', '46'),
 ('45', '99'),
 ('59', '96'),
 ('60', '97'),
 ('62', '69'),
 ('62', '77'),
 ('63', '7'),
 ('63', '70'),
 ('63', '78'),
 ('64', '71'),
 ('64', '79'),
 ('65', '72'),
 ('65', '80'),
 ('66', '9'),
 ('66', '67'),
 ('66', '73'),
 ('66', '81'),
 ('67', '9'),
 ('67', '73'),
 ('67', '74'),
 ('67', '82'),
 ('71', '79'),
 ('72', '80'),
 ('73', '9'),
 ('73', '74'),
 ('81', '9'),
 ('81', '82'),
 ('100', '28'),
 ('100', '31'),
 ('100', '35'),
 ('100', '38'),
 ('100', '121'),
 ('103', '31'),
 ('103', '32'),
 ('103', '38'),
 ('103', '124'),
 ('103', '145'),
 ('104', '32'),
 ('107', '86'),
 ('107', '110'),
 ('110', '86'),
 ('114', '93'),
 ('114', '117'),
 ('117', '93'),
 ('120', '34'),
 ('121', '28'),
 ('121', '35'),
 ('121', '38'),
 ('124', '31'),
 ('124', '38'),
 ('124', '39'),
 ('125', '39'),
 ('127', '85'),
 ('127', '131'),
 ('131', '85'),
 ('134', '92'),
 ('134', '138'),
 ('138', '92'),
 ('141', '27'),
 ('141', '41'),
 ('141', '45'),
 ('141', '99'),
 ('142', '42'),
 ('145', '31'),
 ('145', '45'),
 ('145', '46'),
 ('146', '46'),
 ('176', '177'),
 ('176', '178'),
 ('176', '180'),
 ('176', '191'),
 ('176', '193'),
 ('177', '179'),
 ('177', '181'),
 ('177', '192'),
 ('177', '194'),
 ('177', '196'),
 ('178', '193'),
 ('179', '192'),
 ('179', '194'),
 ('180', '195'),
 ('181', '192'),
 ('181', '196'),
 ('191', '192'),
 ('191', '193'),
 ('191', '195'),
 ('192', '194'),
 ('192', '196'),
 ('193', '195')]

In [15]:
features_corr=features.drop(columns=corr_columns)
features_corr.shape

(24255, 155)

In [25]:
print(corr_columns)
len(corr_columns)

['5', '21', '64', '71', '79', '76', '84', '62', '69', '77', '70', '78', '9', '15', '16', '23', '24', '66', '67', '74', '82', '6', '62', '69', '7', '63', '70', '2', '21', '64', '71', '79', '8', '22', '9', '16', '66', '73', '74', '9', '67', '73', '74', '4', '76', '6', '62', '77', '7', '63', '78', '64', '71', '79', '8', '9', '24', '66', '81', '82', '67', '81', '82', '4', '84', '31', '41', '45', '99', '31', '35', '38', '4', '32', '38', '45', '66', '99', '39', '38', '39', '45', '99', '46', '99', '96', '97', '69', '77', '7', '70', '78', '71', '79', '72', '80', '9', '67', '73', '81', '9', '73', '74', '82', '79', '80', '9', '74', '9', '82', '28', '31', '35', '38', '121', '31', '32', '38', '124', '145', '32', '86', '110', '86', '93', '117', '93', '34', '28', '35', '38', '31', '38', '39', '39', '85', '131', '85', '92', '138', '92', '27', '41', '45', '99', '42', '31', '45', '46', '46', '177', '178', '180', '191', '193', '179', '181', '192', '194', '196', '193', '192', '194', '195', '192', '196', '192', '193', '195', '194', '196', '195']

69

In [17]:
corr1=features_corr.corr(method='pearson')
corr1.head()

,0,1,3,10,11,12,13,14,17,18,...,214,215,216,217,218,219,220,221,222,223
0,1.000000,-0.032734,0.154037,-0.001936,0.431800,0.400600,0.677417,0.045101,0.167077,0.568576,...,0.030724,-0.002891,0.010081,0.152286,0.063903,0.062679,0.068787,-0.145652,0.022463,-0.001100
1,-0.032734,1.000000,-0.013831,0.212555,-0.196244,0.188262,-0.021788,0.156386,-0.017983,0.001486,...,-0.347062,-0.396261,-0.344839,-0.696870,-0.393259,-0.375284,-0.501649,0.561510,-0.030204,-0.008063
3,0.154037,-0.013831,1.000000,-0.007632,0.196238,0.177235,0.377731,0.002447,0.546048,0.189488,...,0.005960,-0.015134,0.010604,0.039140,0.019678,0.034899,0.023327,-0.053992,0.002986,-0.002107
10,-0.001936,0.212555,-0.007632,1.000000,-0.525693,0.581948,0.026791,0.226308,-0.007689,0.048319,...,-0.114478,-0.010014,-0.109519,-0.231138,-0.006392,-0.119582,-0.155100,0.161331,0.014333,0.027566
11,0.431800,-0.196244,0.196238,-0.525693,1.000000,0.124931,0.652285,-0.153428,0.194946,0.638868,...,0.093893,-0.019009,0.106736,0.266501,0.035628,0.132797,0.140330,-0.209972,0.002004,-0.017033

In [18]:
corr_feat1=[]
corr_index1=[]
corr_columns1=[]
for index in corr1.index:
    for column in corr1.columns:
        if index < column and abs(corr1.loc[index,column])>=0.8:
            corr_feat1.append((index,column))
            corr_index1.append(index)
            corr_columns1.append(column)
            
print(len(corr_feat1))
corr_feat1

36

[('11', '19'),
 ('12', '20'),
 ('18', '26'),
 ('18', '29'),
 ('26', '29'),
 ('30', '37'),
 ('30', '44'),
 ('52', '53'),
 ('57', '61'),
 ('89', '90'),
 ('100', '103'),
 ('101', '29'),
 ('103', '104'),
 ('103', '125'),
 ('103', '146'),
 ('104', '125'),
 ('104', '146'),
 ('107', '89'),
 ('111', '90'),
 ('114', '56'),
 ('114', '115'),
 ('116', '95'),
 ('122', '36'),
 ('127', '132'),
 ('134', '136'),
 ('139', '60'),
 ('143', '43'),
 ('153', '155'),
 ('153', '157'),
 ('153', '171'),
 ('155', '173'),
 ('157', '175'),
 ('171', '173'),
 ('171', '175'),
 ('186', '190'),
 ('215', '218')]

In [19]:
features_corr1=features_corr.drop(columns=corr_columns1)
features_corr1.shape

(24255, 126)

In [34]:
cols=list(set(corr_columns+corr_columns1))

In [35]:
len(cols)

98

In [36]:
reject_cols=pd.Series(cols)
reject_cols.to_csv(r'C:\Users\Asus\PredictingRatings\data\reject_cols.csv',sep=',',index=False)

In [37]:
reject_cols.shape

(98,)